### ISSUE TITLE
Create metadata step (2d)

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-deposit-ui#20]
- [ ] Add metadata form - hopefully we can have a standard HTML form
- [ ] Validate form data against JSON schema
- [ ] Highlight metadata fields if an action is required
- [ ] If action is to accept a modification, provide Accept/Reject buttons

Metadata requirements: https://docs.google.com/spreadsheets/d/1eweWbg45kUVh1Wvvjz2nPLngj8PUKEwWdzOjGALGnXs/edit#gid=0

**Comment by jabrah** [comment]
I think the 2nd checkbox can change to general "validation" as I am not sure it matters if it comes from regular form validation, or JSON schema validation

**Comment by jabrah** [comment]
Should move the last checkbox to a separate ticket
